// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhrbnafcdadsqkrsfwdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ocmJuYWZjZGFkc3FrcnNmd2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NTc5MzEsImV4cCI6MjA1NjQzMzkzMX0.2W4LMuDUWS4TLyZ7hClUn-Ukvs00hSn_Qyug9FTE3N8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);